# Generated by Django 3.2.6 on 2021-10-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('phone', models.CharField(max_length=255, verbose_name='telefone')),
                ('address', models.CharField(max_length=255, verbose_name='endereço de entrega')),
                ('cep', models.CharField(max_length=255, verbose_name='CEP')),
                ('more_info', models.TextField(verbose_name='conta pra gente, do que a criança mais gosta')),
                ('relatedness', models.CharField(choices=[('PA', 'Mãe/Pai'), ('GR', 'Avôou Avó'), ('ST', 'Madrasta ou Padrasto'), ('AU', 'Tia ou Tio'), ('BR', 'Irmão ou Irmã'), ('TE', 'Professor(a)'), ('OT', 'Outro')], default='PA', max_length=2)),
                ('kids_name', models.CharField(max_length=255, verbose_name='Nome da criança')),
                ('kids_age', models.IntegerField(verbose_name='Idade da criança')),
                ('kids_gender', models.CharField(choices=[('MA', 'Masculino'), ('FE', 'Feminino'), ('NO', 'Prefiro não responder')], default='NO', max_length=2)),
                ('kids_race', models.CharField(choices=[('WH', 'Branca'), ('PA', 'Parda'), ('BL', 'Preta'), ('YE', 'Amarela'), ('NA', 'Indígena'), ('BN', 'Preta e Indígena')], default='BL', max_length=2)),
                ('subscribing_date', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Assinante',
                'verbose_name_plural': 'Assinantes',
            },
        ),
    ]
