# Generated by Django 3.2.6 on 2021-10-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='kids_gender_raw',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='kids_race_raw',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='relatedness_raw',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='endereço de entrega'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='cep',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='kids_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Idade da criança'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='kids_gender',
            field=models.CharField(blank=True, choices=[('MA', 'Masculino'), ('FE', 'Feminino'), ('NO', 'Prefiro não responder')], default='NO', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='kids_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da criança'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='kids_race',
            field=models.CharField(blank=True, choices=[('WH', 'Branca'), ('PA', 'Parda'), ('BL', 'Preta'), ('YE', 'Amarela'), ('NA', 'Indígena'), ('BN', 'Preta e Indígena')], default='BL', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='more_info',
            field=models.TextField(blank=True, null=True, verbose_name='conta pra gente, do que a criança mais gosta'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='relatedness',
            field=models.CharField(blank=True, choices=[('PA', 'Mãe/Pai'), ('GR', 'Avôou Avó'), ('ST', 'Madrasta ou Padrasto'), ('AU', 'Tia ou Tio'), ('BR', 'Irmão ou Irmã'), ('TE', 'Professor(a)'), ('OT', 'Outro')], default='PA', max_length=2, null=True),
        ),
    ]
