# Generated by Django 3.2.8 on 2021-10-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_subscriber_asaas_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF'),
        ),
    ]
