# Generated by Django 3.2.8 on 2021-10-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_subscriber_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='addressNumber',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='número'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='complement',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='complemento'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='delivery',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='frete para'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='province',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='bairro'),
        ),
    ]
