# Generated by Django 3.2.6 on 2021-11-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20211029_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('phone', models.CharField(max_length=255, verbose_name='Telefone')),
                ('email', models.CharField(max_length=255)),
                ('document', models.CharField(max_length=255, verbose_name='CPF')),
                ('company_document', models.CharField(max_length=255, verbose_name='CNPJ')),
                ('state_register', models.CharField(max_length=255, verbose_name='Inscrição Estadual')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('complement', models.CharField(max_length=255, verbose_name='Complemento')),
                ('number', models.CharField(max_length=255, verbose_name='Número')),
                ('district', models.CharField(max_length=255, verbose_name='Bairro')),
                ('city', models.CharField(max_length=255, verbose_name='Cidade')),
                ('country_id', models.CharField(max_length=255, verbose_name='Sigla País')),
                ('postal_code', models.CharField(max_length=255, verbose_name='CEP')),
                ('note', models.CharField(max_length=255, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Remetente',
            },
        ),
    ]
