# Generated by Django 3.2.6 on 2021-11-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observações de endereço'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='state_initials',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
    ]
