# Generated by Django 3.2.6 on 2021-12-03 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20211125_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sender',
            options={'verbose_name': 'Remetente', 'verbose_name_plural': 'Remetente'},
        ),
    ]
