# Generated by Django 3.2.6 on 2021-12-09 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_sender_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data')),
                ('text', models.CharField(max_length=255, verbose_name='texto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descrição')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='dados')),
            ],
            options={
                'verbose_name': 'aviso',
                'verbose_name_plural': 'avisos',
            },
        ),
    ]
