# Generated by Django 3.2.6 on 2021-12-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_warning'),
    ]

    operations = [
        migrations.AddField(
            model_name='warning',
            name='solution',
            field=models.TextField(blank=True, null=True, verbose_name='solução'),
        ),
    ]
