# Generated by Django 3.2.6 on 2021-12-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_warning_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='jadlog_agency_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Agência Jadlog'),
        ),
        migrations.AddField(
            model_name='sender',
            name='jadlog_agency_options',
            field=models.JSONField(default=dict, verbose_name='Opções Agências Jadlog'),
        ),
    ]
