# Generated by Django 3.2.6 on 2021-12-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20211209_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='endereço de entrega'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='addressNumber',
            field=models.CharField(max_length=255, null=True, verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='cep',
            field=models.CharField(max_length=255, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='city',
            field=models.CharField(max_length=255, null=True, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='cpf',
            field=models.CharField(max_length=11, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='phone',
            field=models.CharField(max_length=255, null=True, verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='province',
            field=models.CharField(max_length=255, null=True, verbose_name='bairro'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='state_initials',
            field=models.CharField(max_length=2, null=True, verbose_name='UF'),
        ),
    ]
