# Generated by Django 3.2.6 on 2021-12-15 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20211210_1708'),
        ('finance', '0002_remove_subscription_asaas_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='billingType',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de cobrança'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='due_date',
            field=models.DateTimeField(null=True, verbose_name='Data de vencimento'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID da fatura'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.subscription', verbose_name='Assinatura'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='asaas_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Asaas'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='billingType',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de cobrança'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='cycle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ciclo'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Excluído'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscriber',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.subscriber', verbose_name='Assinante'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor'),
        ),
    ]
