# Generated by Django 3.2.6 on 2021-12-22 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20211215_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.subscription', verbose_name='Assinatura'),
        ),
    ]
