# Generated by Django 3.2.6 on 2021-11-24 15:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_auto_20211029_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('width', models.FloatField(blank=True, null=True, verbose_name='Largura')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Altura')),
                ('length', models.FloatField(blank=True, null=True, verbose_name='Comprimento')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Peso')),
            ],
            options={
                'verbose_name': 'Caixa',
                'verbose_name_plural': 'Caixas',
            },
        ),
        migrations.CreateModel(
            name='BoxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
            },
        ),
        migrations.CreateModel(
            name='ShippingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Preço')),
                ('delivery_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo de entrega (em dias)')),
                ('delivery_time_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo de entrega mínimo (em dias)')),
                ('delivery_time_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo de entrega máximo (em dias)')),
                ('melhor_envio_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Melhor Envio ID')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('insurance_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Seguro')),
                ('receipt', models.BooleanField(default=False, verbose_name='Aviso de recebimento')),
                ('own_hand', models.BooleanField(default=False, verbose_name='Mãos próprias')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shippings', to='box.box', verbose_name='Caixa')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shippings', to='account.subscriber', verbose_name='Destinatário')),
                ('shipping_option_selected', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='box.shippingoption', verbose_name='Opção de Envio Selecionada')),
                ('shipping_options', models.ManyToManyField(blank=True, related_name='_box_shipping_shipping_options_+', to='box.ShippingOption', verbose_name='Opções de Envio')),
            ],
            options={
                'verbose_name': 'Shipping',
                'verbose_name_plural': 'Shippings',
            },
        ),
        migrations.AddField(
            model_name='box',
            name='items',
            field=models.ManyToManyField(blank=True, to='box.BoxItem', verbose_name='Itens'),
        ),
    ]
