# Generated by Django 3.2.6 on 2021-11-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipping',
            options={'verbose_name': 'Envio', 'verbose_name_plural': 'Envios'},
        ),
        migrations.AlterModelOptions(
            name='shippingoption',
            options={'verbose_name': 'Opção de Envio', 'verbose_name_plural': 'Opções de Envio'},
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='insurance_value',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='own_hand',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='receipt',
        ),
        migrations.AddField(
            model_name='box',
            name='insurance_value',
            field=models.FloatField(default=0, verbose_name='Valor do Seguro'),
        ),
        migrations.AddField(
            model_name='box',
            name='own_hand',
            field=models.BooleanField(default=False, verbose_name='Mãos próprias'),
        ),
        migrations.AddField(
            model_name='box',
            name='receipt',
            field=models.BooleanField(default=False, verbose_name='Aviso de recebimento'),
        ),
        migrations.AlterField(
            model_name='box',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Altura (cm)'),
        ),
        migrations.AlterField(
            model_name='box',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='Comprimento (cm)'),
        ),
        migrations.AlterField(
            model_name='box',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='box',
            name='width',
            field=models.FloatField(blank=True, null=True, verbose_name='Largura (cm)'),
        ),
    ]
