# Generated by Django 3.2.6 on 2021-11-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0002_auto_20211124_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='label',
            field=models.JSONField(blank=True, null=True, verbose_name='Dados da Etiqueta'),
        ),
    ]
