# Generated by Django 3.2.6 on 2021-12-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0006_auto_20211203_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='letter',
            field=models.FileField(blank=True, null=True, upload_to='cartas/', verbose_name='Carta de orientação'),
        ),
        migrations.AddField(
            model_name='boxitem',
            name='type',
            field=models.CharField(choices=[('LI', 'Livro'), ('TO', 'Brinquedo'), ('PR', 'Brinde'), ('OT', 'Outro')], default='OT', max_length=3, verbose_name='Tipo'),
        ),
    ]
