# Generated by Django 3.2.6 on 2021-12-02 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('box', '0004_remove_shipping_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(verbose_name='Data de criação')),
                ('total', models.FloatField(default=0, verbose_name='Preço')),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('full_info', models.JSONField(blank=True, null=True, verbose_name='Informações completas')),
            ],
            options={
                'verbose_name': 'Compra de etiquetas',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('price', models.FloatField(default=0, verbose_name='Preço')),
                ('format', models.CharField(blank=True, max_length=255, null=True, verbose_name='Formato')),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('protocol', models.CharField(blank=True, max_length=255, null=True, verbose_name='Protocolo')),
                ('volumes', models.JSONField(blank=True, null=True)),
                ('full_info', models.JSONField(blank=True, null=True, verbose_name='Informações completas')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkout.purchase')),
                ('shipping', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='box.shipping')),
            ],
            options={
                'verbose_name': 'Etiqueta',
            },
        ),
    ]
