# Generated by Django 3.2.6 on 2021-12-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Compra de etiqueta'},
        ),
        migrations.AddField(
            model_name='purchase',
            name='print_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
